### ISSUE TITLE
500 error on /autocomplete/:folder/:text endpoint

### ISSUE THREAD

**Issue by padsbanger** [formstack/front-end-project-api#1]
Hello,

Autocomplete functionality is not working.

When accessing endpoint like: `http://localhost:8080/api/autocomplete/js/a`

I am getting 500 error, and following log:

```
TypeError: Cannot read property &#39;type&#39; of undefined
<br> &nbsp; &nbsp;at c:\Users\strielok\Desktop\front-end-project-api-master\front-end-project-api-master\server.js:118:27
    <br> &nbsp; &nbsp;at Layer.handle [as handle_request] (c:\Users\strielok\Desktop\front-end-project-api-master\front-end-project-api-master\node_modules\express\lib\router\layer.js:82:5)
        <br> &nbsp; &nbsp;at next (c:\Users\strielok\Desktop\front-end-project-api-master\front-end-project-api-master\node_modules\express\lib\router\route.js:100:13)
            <br> &nbsp; &nbsp;at Route.dispatch (c:\Users\strielok\Desktop\front-end-project-api-master\front-end-project-api-master\node_modules\express\lib\router\route.js:81:3)
                <br> &nbsp; &nbsp;at Layer.handle [as handle_request] (c:\Users\strielok\Desktop\front-end-project-api-master\front-end-project-api-master\node_modules\express\lib\router\layer.js:82:5)
                    <br> &nbsp; &nbsp;at c:\Users\strielok\Desktop\front-end-project-api-master\front-end-project-api-master\node_modules\express\lib\router\index.js:234:24
                        <br> &nbsp; &nbsp;at param (c:\Users\strielok\Desktop\front-end-project-api-master\front-end-project-api-master\node_modules\express\lib\router\index.js:331:14)
                            <br> &nbsp; &nbsp;at param (c:\Users\strielok\Desktop\front-end-project-api-master\front-end-project-api-master\node_modules\express\lib\router\index.js:347:14)
                                <br> &nbsp; &nbsp;at param (c:\Users\strielok\Desktop\front-end-project-api-master\front-end-project-api-master\node_modules\express\lib\router\index.js:347:14)
                                    <br> &nbsp; &nbsp;at Function.proto.process_params (c:\Users\strielok\Desktop\front-end-project-api-master\front-end-project-api-master\node_modules\express\lib\router\index.js:391:3)
```

**Comment by Kraku** [comment]
Use id of that folder, for example:

```
http://localhost:8080/api/autocomplete/1/a
```

**Comment by padsbanger** [comment]
Ok, thanks.
